packages:
  - packages/*
  - apps/*
catalogs:
  discordjs:
    discord.js: ^14.25.1
  build:
    typescript: ^5.9.3
    tsdown: ^0.20.0-beta.3
  workflow:
    workflow: ^4.0.1-beta.50
    '@workflow/builders': ^4.0.1-beta.41
    '@workflow/rollup': '^4.0.0-beta.8'
