import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { COMMANDKIT_CWD, COMMANDKIT_IS_DEV } from './constants';
import { existsSync } from 'node:fs';

export const COMMANDKIT_TYPES_DIRECTORY = '.commandkit';
export const COMMANDKIT_TYPES_FILE = 'types.ts';
export const COMMANDKIT_ENV_FILE = 'commandkit-env.d.ts';

export function getTypesFilePath() {
  return join(
    COMMANDKIT_CWD,
    COMMANDKIT_TYPES_DIRECTORY,
    COMMANDKIT_TYPES_FILE,
  );
}

function getEnvFilePath() {
  return join(COMMANDKIT_CWD, COMMANDKIT_ENV_FILE);
}

async function ensureCommandkitEnvFile() {
  const envPath = getEnvFilePath();
  const content = `/// <reference path="./${COMMANDKIT_TYPES_DIRECTORY}/types" />\n`;
  await writeFile(envPath, content, 'utf8');
}

async function writeTypesContent(names: string[] = []) {
  const typesPath = getTypesFilePath();

  const entryLines = names
    .sort((a, b) => a.localeCompare(b))
    .map((name) => `    ${JSON.stringify(name)}: true;`)
    .join('\n');

  const registryBody = entryLines || '    __commandkit_wide__: true;';

  const declaration = `// Auto-generated by CommandKit\nexport {};\ndeclare global {\n  namespace CommandKitTypes {\n    interface Registry {\n${registryBody}\n    }\n  }\n}\n`;

  await mkdir(dirname(typesPath), { recursive: true }).catch(() => {});
  await writeFile(typesPath, declaration, 'utf8');

  return typesPath;
}

/**
 * @private
 */
export async function generateTypesPackage(force = false) {
  const location = getTypesFilePath();
  if (!COMMANDKIT_IS_DEV && !force) return location;

  await writeTypesContent();
  await ensureCommandkitEnvFile();

  return location;
}

/**
 * @private
 */
export async function rewriteCommandDeclaration(data: string[] | string) {
  const type = getTypesFilePath();

  if (!existsSync(dirname(type))) {
    await mkdir(dirname(type), { recursive: true }).catch(() => {});
  }

  const names = Array.isArray(data)
    ? data
    : data
        .replace(/type\s+CommandTypeData\s*=\s*/g, '')
        .split('|')
        .map((part) => part.trim().replace(/^"|"$/g, ''))
        .filter(Boolean)
        .filter((part) => part !== 'string');

  const dedupedNames = Array.from(new Set(names));

  await writeTypesContent(dedupedNames);
  await ensureCommandkitEnvFile();
}
